        Route::resource('barang', BarangController::class);
        Route::resource('mitra', MitraController::class);
        Route::resource('supplier', SupplierController::class);
        Route::resource('category', CategoryController::class);
        Route::resource('produksi', ProduksiController::class);
        Route::resource('pengemasan', ProduksiController::class);
        Route::resource('profile', ProfileController::class);
        Route::resource('rak', RakController::class);
        Route::resource('satuan', SatuanController::class);
        Route::resource('isirak', IsiRakController::class);
        Route::resource('history', HistoryController::class);
        Route::resource('cetakpdf', CetakPDFController::class);
        Route::resource('distribusi', DistribusiController::class);
        Route::resource('konversi', KonversiController::class);
        Route::get('settings', [SettingsController::class, 'index'])->name('admin.settings.index');
        Route::get('penjualan/create', [HistoryController::class, 'penjualan_create'])->name('admin.penjualan.create');
        Route::get('settings', [SettingsController::class, 'edit'])->name('admin.settings.edit');
        Route::put('settings', [SettingsController::class, 'update'])->name('admin.settings.update');
        Route::get('penjualan', [HistoryController::class, 'index'])->name('penjualan.index');
        Route::get('pembelian', [HistoryController::class, 'index'])->name('pembelian.index');
        Route::get('distribusihistory', [Distribusi2Controller::class, 'index'])->name('distribusishow.index');
        Route::get('produksihistory', [ProduksiHistoryController::class, 'index'])->name('produksihistory.index');
        Route::get('pengemasan/create', [PengemasanController::class, 'create'])->name('pengemasan.create');
        Route::get('pengemasanhistory', [PengemasanController::class, 'index'])->name('pengemasan.index');